name: MERN Stack CI Test

on:
  push:
    branches:
      - main

jobs:
  backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Backend Dependencies
        working-directory: CISE_Repos/Week\ 3/MERN_Book_App_api
        run: npm install

      - name: Run Backend Tests
        working-directory: CISE_Repos/Week\ 3/MERN_Book_App_api
        run: npm test

  frontend:
    name: Build and Test Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Frontend Dependencies
        working-directory: CISE_Repos/Week\ 3/mern_book_app_client
        run: npm install

      - name: Build Frontend
        working-directory: CISE_Repos/Week\ 3/mern_book_app_client
        run: npm run build

      - name: Run Frontend Tests
        working-directory: CISE_Repos/Week\ 3/mern_book_app_client
        run: npm test
